# Generated by Django 5.2.3 on 2025-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
