# Generated by Django 5.2.17 on 2026-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
