# Generated by Django 5.2.17 on 2026-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deletionfollowup_filedeletionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='complimentary_plan',
            field=models.CharField(blank=True, choices=[('', 'None'), ('premium', 'Premium'), ('pro', 'Pro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complimentary_reason',
            field=models.CharField(blank=True, choices=[('reviewer', 'App reviewer'), ('family', 'Family'), ('friend', 'Friend'), ('tester', 'Tester'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='complimentary_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
