# Generated by Django 5.2 on 2025-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_bot_description_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='personality',
            field=models.TextField(default='I am a helpful and friendly assistant.'),
        ),
    ]
