# Generated by Django 5.2 on 2025-05-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bots.bot'),
        ),
    ]
