# Generated by Django 5.2 on 2025-05-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_chatmessage_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('fitness', 'Fitness'), ('finance', 'Finance'), ('funny', 'Funny'), ('support', 'Support'), ('tech', 'Tech')], default='general', max_length=20),
        ),
    ]
