# Generated by Django 4.2 on 2025-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_bot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('career', 'Career'), ('community', 'Community'), ('culture', 'Culture'), ('current_affairs', 'Current Affairs'), ('education', 'Education'), ('entrepreneurship', 'Entrepreneurship'), ('entertainment', 'Entertainment'), ('environment', 'Environment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('fitness', 'Fitness'), ('food', 'Food'), ('funny', 'Funny'), ('gaming', 'Gaming'), ('gardening', 'Gardening'), ('general', 'General'), ('hobbies', 'Hobbies'), ('history', 'History'), ('home_improvement', 'Home Improvement'), ('innovation', 'Innovation'), ('interview_preparation', 'Interview Preparation'), ('job_search', 'Job Search'), ('language', 'Language'), ('leadership', 'Leadership'), ('lifestyle', 'Lifestyle'), ('local', 'Local'), ('management', 'Management'), ('marketing', 'Marketing'), ('mental_health', 'Mental Health'), ('music', 'Music'), ('news', 'News'), ('other', 'Other'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('resume_building', 'Resume Building'), ('sales', 'Sales'), ('science', 'Science'), ('self_improvement', 'Self Improvement'), ('shopping', 'Shopping'), ('society', 'Society'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('support', 'Support'), ('sustainability', 'Sustainability'), ('tech', 'Tech'), ('technology', 'Technology'), ('therapy', 'Therapy'), ('travel', 'Travel'), ('wellbeing', 'Wellbeing'), ('wellness', 'Wellness')], default='general', max_length=23),
        ),
        migrations.AlterField(
            model_name='bot',
            name='personality',
            field=models.TextField(default='AI assistant.'),
        ),
    ]
