# Generated by Django 4.2 on 2025-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_bot_category_alter_bot_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='personality',
            field=models.TextField(default='I am a helpful and friendly assistant.'),
        ),
    ]
