# Generated by Django 4.2 on 2025-06-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0007_alter_bot_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('career', 'Career'), ('community', 'Community'), ('culture', 'Culture'), ('current_affairs', 'Current Affairs'), ('education', 'Education'), ('entrepreneurship', 'Entrepreneurship'), ('entertainment', 'Entertainment'), ('environment', 'Environment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('fitness', 'Fitness'), ('food', 'Food'), ('funny', 'Funny'), ('gaming', 'Gaming'), ('gardening', 'Gardening'), ('general', 'General'), ('hobbies', 'Hobbies'), ('history', 'History'), ('home_improvement', 'Home Improvement'), ('innovation', 'Innovation'), ('interview_preparation', 'Interview Preparation'), ('job_search', 'Job Search'), ('language', 'Language'), ('leadership', 'Leadership'), ('lifestyle', 'Lifestyle'), ('local', 'Local'), ('management', 'Management'), ('marketing', 'Marketing'), ('mental_health', 'Mental Health'), ('music', 'Music'), ('news', 'News'), ('other', 'Other'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('resume_building', 'Resume Building'), ('sales', 'Sales'), ('science', 'Science'), ('self_improvement', 'Self Improvement'), ('shopping', 'Shopping'), ('society', 'Society'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('support', 'Support'), ('sustainability', 'Sustainability'), ('tech', 'Tech'), ('technology', 'Technology'), ('therapy', 'Therapy'), ('travel', 'Travel'), ('wellbeing', 'Wellbeing'), ('wellness', 'Wellness'), ('3-D Printing', '3-D Printing')], default='general', max_length=23),
        ),
        migrations.CreateModel(
            name='BotUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
