# Generated by Django 4.2 on 2025-06-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_bot_category_botusagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUsageLog',
        ),
    ]
