# Generated by Django 4.2 on 2025-06-25 16:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0010_knowledgebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(upload_to='knowledge_files/'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bots.knowledgebase')),
            ],
        ),
    ]
