# Generated by Django 4.2 on 2025-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_alter_knowledgebase_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
