# Generated by Django 4.2 on 2025-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_alter_knowledgechunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('personality', models.TextField(default='I am a helpful and friendly assistant.')),
                ('category', models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('career', 'Career'), ('community', 'Community'), ('culture', 'Culture'), ('current_affairs', 'Current Affairs'), ('education', 'Education'), ('entrepreneurship', 'Entrepreneurship'), ('entertainment', 'Entertainment'), ('environment', 'Environment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('fitness', 'Fitness'), ('food', 'Food'), ('funny', 'Funny'), ('gaming', 'Gaming'), ('gardening', 'Gardening'), ('general', 'General'), ('hobbies', 'Hobbies'), ('history', 'History'), ('home_improvement', 'Home Improvement'), ('innovation', 'Innovation'), ('interview_preparation', 'Interview Preparation'), ('job_search', 'Job Search'), ('language', 'Language'), ('leadership', 'Leadership'), ('lifestyle', 'Lifestyle'), ('local', 'Local'), ('management', 'Management'), ('marketing', 'Marketing'), ('mental_health', 'Mental Health'), ('music', 'Music'), ('news', 'News'), ('other', 'Other'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('resume_building', 'Resume Building'), ('sales', 'Sales'), ('science', 'Science'), ('self_improvement', 'Self Improvement'), ('shopping', 'Shopping'), ('society', 'Society'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('support', 'Support'), ('sustainability', 'Sustainability'), ('tech', 'Tech'), ('technology', 'Technology'), ('therapy', 'Therapy'), ('travel', 'Travel'), ('wellbeing', 'Wellbeing'), ('wellness', 'Wellness'), ('3-D Printing', '3-D Printing')], default='general', max_length=23)),
            ],
        ),
    ]
