# Generated by Django 5.2.3 on 2026-08-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_botusagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('career', 'Career'), ('community', 'Community'), ('culture', 'Culture'), ('current_affairs', 'Current Affairs'), ('education', 'Education'), ('entrepreneurship', 'Entrepreneurship'), ('entertainment', 'Entertainment'), ('environment', 'Environment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('fitness', 'Fitness'), ('food', 'Food'), ('funny', 'Funny'), ('gaming', 'Gaming'), ('gardening', 'Gardening'), ('general', 'General'), ('hobbies', 'Hobbies'), ('history', 'History'), ('home_improvement', 'Home Improvement'), ('innovation', 'Innovation'), ('interview_preparation', 'Interview Preparation'), ('job_search', 'Job Search'), ('language', 'Language'), ('leadership', 'Leadership'), ('lifestyle', 'Lifestyle'), ('local', 'Local'), ('management', 'Management'), ('marketing', 'Marketing'), ('mental_health', 'Mental Health'), ('music', 'Music'), ('news', 'News'), ('other', 'Other'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('resume_building', 'Resume Building'), ('sales', 'Sales'), ('science', 'Science'), ('self_improvement', 'Self Improvement'), ('shopping', 'Shopping'), ('society', 'Society'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('support', 'Support'), ('sustainability', 'Sustainability'), ('tech', 'Tech'), ('technology', 'Technology'), ('therapy', 'Therapy'), ('travel', 'Travel'), ('wellbeing', 'Wellbeing'), ('wellness', 'Wellness'), ('3-D Printing', '3-D Printing')], default='general', help_text='Thematic category that shapes bot behavior.', max_length=23),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the bot.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text='Name of the bot.', max_length=100),
        ),
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(help_text='User who owns the bot.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bot',
            name='personality',
            field=models.TextField(default='I am a helpful and friendly assistant.', help_text="Defines the assistant's tone and response style."),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('business', 'Business'), ('career', 'Career'), ('community', 'Community'), ('culture', 'Culture'), ('current_affairs', 'Current Affairs'), ('education', 'Education'), ('entrepreneurship', 'Entrepreneurship'), ('entertainment', 'Entertainment'), ('environment', 'Environment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('fitness', 'Fitness'), ('food', 'Food'), ('funny', 'Funny'), ('gaming', 'Gaming'), ('gardening', 'Gardening'), ('general', 'General'), ('hobbies', 'Hobbies'), ('history', 'History'), ('home_improvement', 'Home Improvement'), ('innovation', 'Innovation'), ('interview_preparation', 'Interview Preparation'), ('job_search', 'Job Search'), ('language', 'Language'), ('leadership', 'Leadership'), ('lifestyle', 'Lifestyle'), ('local', 'Local'), ('management', 'Management'), ('marketing', 'Marketing'), ('mental_health', 'Mental Health'), ('music', 'Music'), ('news', 'News'), ('other', 'Other'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('resume_building', 'Resume Building'), ('sales', 'Sales'), ('science', 'Science'), ('self_improvement', 'Self Improvement'), ('shopping', 'Shopping'), ('society', 'Society'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('support', 'Support'), ('sustainability', 'Sustainability'), ('tech', 'Tech'), ('technology', 'Technology'), ('therapy', 'Therapy'), ('travel', 'Travel'), ('wellbeing', 'Wellbeing'), ('wellness', 'Wellness'), ('3-D Printing', '3-D Printing')], default='general', help_text='Category to classify template bots.', max_length=23),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the template.'),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='bottemplate',
            name='personality',
            field=models.TextField(default='I am a helpful and friendly assistant.', help_text='Default personality used by bots created from this template.'),
        ),
        migrations.AlterField(
            model_name='botusagelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this usage was recorded.'),
        ),
        migrations.AlterField(
            model_name='botusagelog',
            name='tokens_used',
            field=models.IntegerField(help_text='Total number of tokens used during the session.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(help_text='Message content.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], help_text='Indicates whether the message was sent by the user or the bot.', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of the message.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='bot',
            field=models.ForeignKey(help_text='The bot this knowledge file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(help_text='Uploaded document file used as bot knowledge.', upload_to='knowledge_files/'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the file was uploaded.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the file (can be null if user is deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the chunk was created.'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, help_text='The vector embedding of this chunk for semantic search.', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='knowledge_file',
            field=models.ForeignKey(help_text='The parent knowledge file this chunk belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bots.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='text',
            field=models.TextField(help_text='The actual content of this chunk.'),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_bot_per_user'),
        ),
    ]
