# Generated by Django 5.2.3 on 2026-09-08 21:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_bot_sender_to_assistant(apps, schema_editor):
    """
    Convert legacy chat messages from the old
    'bot' sender value to 'assistant'.
    """

    ChatMessage = apps.get_model(
        "bots",
        "ChatMessage",
    )

    ChatMessage.objects.filter(
        sender="bot",
    ).update(
        sender="assistant",
    )


def migrate_assistant_sender_to_bot(apps, schema_editor):
    """
    Restore the legacy sender value if this
    migration is reversed.
    """

    ChatMessage = apps.get_model(
        "bots",
        "ChatMessage",
    )

    ChatMessage.objects.filter(
        sender="assistant",
    ).update(
        sender="bot",
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "bots",
            "0015_alter_bot_category_alter_bot_created_at_and_more",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["timestamp"],
            },
        ),

        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                ],
                help_text=(
                    "Indicates whether the message was sent "
                    "by the user or the assistant."
                ),
                max_length=10,
            ),
        ),

        migrations.RunPython(
            migrate_bot_sender_to_assistant,
            migrate_assistant_sender_to_bot,
        ),

        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text=(
                            "Public identifier used by web, "
                            "API, and mobile clients."
                        ),
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Optional conversation title."
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text=(
                            "Timestamp when the conversation "
                            "was created."
                        ),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            "Timestamp when the conversation "
                            "was last updated."
                        ),
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        help_text=(
                            "The bot used in this conversation."
                        ),
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name="conversations",
                        to="bots.bot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=(
                            "The user who owns this conversation."
                        ),
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name="bot_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-updated_at",
                    "-created_at",
                ],
            },
        ),

        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Conversation this message belongs to. "
                    "Legacy messages may not have a conversation."
                ),
                null=True,
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="messages",
                to="bots.conversation",
            ),
        ),
    ]