# Generated by Django 5.2.17 on 2026-09-11 19:38

from django.db import migrations, models


def backfill_source_size_bytes(apps, schema_editor):
    """
    Backfill Knowledge storage usage for existing records.

    Prefer the original uploaded file size when the file is
    still available. If it is unavailable, estimate the size
    from the stored Knowledge chunks instead.
    """
    KnowledgeBase = apps.get_model(
        "bots",
        "KnowledgeBase",
    )
    KnowledgeChunk = apps.get_model(
        "bots",
        "KnowledgeChunk",
    )

    for knowledge in KnowledgeBase.objects.all().iterator():
        source_size_bytes = 0

        if knowledge.file and knowledge.file.name:
            try:
                source_size_bytes = knowledge.file.size
            except Exception:
                source_size_bytes = 0

        if source_size_bytes == 0:
            chunk_texts = KnowledgeChunk.objects.filter(
                knowledge_file_id=knowledge.pk,
            ).values_list(
                "text",
                flat=True,
            )

            source_size_bytes = sum(
                len((text or "").encode("utf-8"))
                for text in chunk_texts
            )

        KnowledgeBase.objects.filter(
            pk=knowledge.pk,
        ).update(
            source_size_bytes=source_size_bytes,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "bots",
            "0016_alter_chatmessage_options_alter_chatmessage_sender_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="source_size_bytes",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text=(
                    "Size in bytes of the uploaded file or "
                    "manual text stored as Knowledge."
                ),
            ),
        ),
        migrations.RunPython(
            backfill_source_size_bytes,
            migrations.RunPython.noop,
        ),
    ]