# Generated by Django 5.2.17 on 2026-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_knowledgebase_source_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar_icon',
            field=models.CharField(choices=[('default', 'None (current appearance)'), ('robot', '🤖 Robot'), ('sparkles', '✨ Sparkles'), ('book', '📚 Books'), ('briefcase', '💼 Briefcase')], default='default', max_length=9),
        ),
        migrations.AddField(
            model_name='bot',
            name='response_length',
            field=models.CharField(choices=[('default', 'Use personality & instructions'), ('concise', 'Concise'), ('detailed', 'Detailed')], default='default', max_length=8),
        ),
        migrations.AddField(
            model_name='bot',
            name='response_tone',
            field=models.CharField(choices=[('default', 'Use personality & instructions'), ('friendly', 'Friendly'), ('professional', 'Professional')], default='default', max_length=12),
        ),
    ]
