# Generated by Django 5.2.17 on 2026-10-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_ai_response_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='communication_style',
            field=models.CharField(choices=[('default', 'Use existing instructions'), ('formal', 'Formal'), ('casual', 'Casual'), ('educational', 'Educational'), ('technical', 'Technical')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='bot',
            name='custom_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='default_language',
            field=models.CharField(choices=[('auto', 'Automatic'), ('en', 'English'), ('sv', 'Swedish')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='bot',
            name='proactivity',
            field=models.CharField(choices=[('default', 'Use existing instructions'), ('minimal', 'Minimal'), ('balanced', 'Balanced'), ('proactive', 'Proactive')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='bot',
            name='response_structure',
            field=models.CharField(choices=[('default', 'Automatic'), ('paragraphs', 'Paragraphs'), ('bullet_points', 'Bullet points'), ('step_by_step', 'Step by step')], default='default', max_length=16),
        ),
    ]
