# Generated by Django 5.2.17 on 2026-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_alter_bot_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='knowledge_activation_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('on_request', 'On request'), ('always', 'Always')], default='automatic', help_text='Choose when this assistant searches its Knowledge Base.', max_length=16),
        ),
    ]
