# Generated by Django 5.2.17 on 2026-09-09 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_subscription_cancel_at_period_end_and_more'),
        ('ai_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('plan', models.CharField(max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success_url', models.TextField()),
                ('cancel_url', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
