# Generated by Django 5.2.17 on 2026-09-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_payments', '0002_checkoutattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=320, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
