# Generated by Django 5.2.17 on 2026-09-10 09:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_subscription_cancel_at_period_end_and_more'),
        ('ai_payments', '0004_subscriptionrecovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action', models.CharField(max_length=20)),
                ('source', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('schedule_id', models.CharField(blank=True, max_length=255)),
                ('target_price', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='confirming', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
