# Generated by Django 5.2.17 on 2026-09-30 10:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unique_username_case_insensitive'),
        ('ai_payments', '0005_subscriptionchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=10)),
                ('environment', models.CharField(max_length=12)),
                ('event_id', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'environment', 'event_id'), name='unique_store_event')],
            },
        ),
        migrations.CreateModel(
            name='StoreIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_identity', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StorePurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=10)),
                ('environment', models.CharField(max_length=12)),
                ('reference', models.CharField(max_length=128)),
                ('encrypted_token', models.TextField(blank=True)),
                ('product_id', models.CharField(max_length=255)),
                ('base_plan_id', models.CharField(blank=True, max_length=63)),
                ('plan', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField(null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_payments.storeidentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'environment', 'reference'), name='unique_store_subscription')],
            },
        ),
    ]
