# Generated by Django 5.2.3 on 2025-07-03 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dashboard', '0001_initial'),
        ('bots', '0014_botusagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='botusagelog',
            old_name='token_count',
            new_name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='botusagelog',
            name='message',
        ),
        migrations.AlterField(
            model_name='botusagelog',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_bot_usage_logs', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='botusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_bot_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
