# Generated by Django 5.2.3 on 2026-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dashboard', '0002_rename_token_count_botusagelog_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusagelog',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botusagelog',
            name='model',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='botusagelog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
